Fix DROP DATABASE for databases with many ACLs
Commit c66a7d75e652 modified DROP DATABASE so that if interrupted, the
database is known to be invalid and connection attempts are rejected.
The implementation performs in-place update setting a flag in the
pg_database row, to make sure it's not forgotten during rollback.

For databases with many ACLs, this may however fail:

  ERROR:  wrong tuple length

This happens because with many ACLs, the pg_database row has a TOASTed
attribute. The code reads the de-toasted tuple from syscache, but the
in-place update expects the tuple length to match the on-disk tuple.

Fix by reading the tuple from the catalog directly, just like in other
places doing in-place updates.

Report and fix by Ayush Tiwari. Backpatch to 12. The DROP DATABASE fix
was backpatched to 11, but 11 is already EOL.

Reported-by: Ayush Tiwari
Author: Ayush Tiwari
Reviewed-by: Tomas Vondra
Backpatch-through: 12
Discussion: https://postgr.es/m/CAJTYsWWNkCt+-UnMhg=BiCD3Mh8c2JdHLofPxsW3m2dkDFw8RA@mail.gmail.com